# Generated by Django 2.2.5 on 2019-09-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190914_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='PointVisit',
        ),
    ]
