# Generated by Django 2.2.5 on 2019-09-15 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190915_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointuser',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=127),
            preserve_default=False,
        ),
    ]
